---
title: "P8105 HW 1"
output: github_document
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(ggplot2)
library(tibble)
```

## Problem 1

This data has the following variables listed: species, island, bill length (mm), bill depth (mm), flipper length (mm), body mass (g), sex, and year. This particular dataset has 8 columns and 344 rows. 

```{r}
mean(penguins[["flipper_length_mm"]], na.rm = TRUE)
```

Here is the scatterplot of flipper_length_mm (y) vs, bill_length_mm (x). 

```{r}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point(size = 2)
```

```{r}
ggsave("flipper_length_mm vs. bill_length_mm.png")
```

## Problem 2

```{r}
sample_df = tibble(
  random_sample = rnorm(10), 
  vec_char = c("red", "orange", "yellow", "blue", "green", "pink", "purple", "black", "white", "gray" ),
  greater_than_zero = random_sample > 0,
  vec_factor = factor(sample(c("Level 1", "Level 2", "Level 3"), 10, replace = TRUE))
)
```

```{r}
print(sample_df)
```

```{r}
mean_random_sample = mean(sample_df[["random_sample"]])
print(mean_random_sample)
```

```{r}
mean_greater_than_zero = mean(sample_df[["greater_than_zero"]])
print(mean_random_sample)
```

```{r}
mean_vec_factor = mean(as.numeric(sample_df[["vec_factor"]])) 
print(mean_vec_factor)
```

The only variable we cannot take the mean of is character vector due to the data not being quantifable. 
